In [1]:
import numpy as np
import pandas as pd

In [2]:
##Q.1 Explain the difference between a Python list and a NumPy array in terms of memory usage and performance.
##Then, write a program that creates both and performs element-wise multiplication.
import numpy as np

list1 = [1,2,3]
list2 = [4,5,6]

arr1 = np.array(list1)
arr2 = np.array(list2)

print(arr1 * arr2)

[ 4 10 18]


In [3]:
#Q.2 What is broadcasting in NumPy?
#Create a 3×3 NumPy array and add a 1D array to it using broadcasting. Explain how NumPy applies the operation internally.
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

one_d = np.array([10,20,30])

result = arr + one_d
print(result)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [4]:
#Q.3 What are missing values in Pandas and how are they represented?
#Create a DataFrame with missing values and write code to:

#• Detect missing values
#• Replace them with the column mean

#Explain each step.

import pandas as pd
import numpy as np

data = {
    "Marks":[80, np.nan, 60, 90],
    "Age":[20,22,np.nan,21]
}

df = pd.DataFrame(data)

# detect missing
print(df.isnull())

# replace with mean
df["Marks"].fillna(df["Marks"].mean(), inplace=True)
df["Age"].fillna(df["Age"].mean(), inplace=True)

print(df)

   Marks    Age
0  False  False
1   True  False
2  False   True
3  False  False
       Marks   Age
0  80.000000  20.0
1  76.666667  22.0
2  60.000000  21.0
3  90.000000  21.0


/tmp/ipython-input-1228644923.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Marks"].fillna(df["Marks"].mean(), inplace=True)
/tmp/ipython-input-1228644923.py:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', 

In [5]:
#Q.4 Explain boolean indexing in NumPy or Pandas.
#Create a DataFrame with at least 5 columns and filter rows based on two conditions using logical operators. Explain how filtering works internally.
data = {
    "Name":["A","B","C","D"],
    "Age":[20,25,30,22],
    "Marks":[80,55,90,40],
    "City":["A","B","A","C"],
    "Dept":["IT","HR","IT","Sales"]
}

df = pd.DataFrame(data)

filtered = df[(df["Age"]>21) & (df["Marks"]>50)]
print(filtered)

  Name  Age  Marks City Dept
1    B   25     55    B   HR
2    C   30     90    A   IT


In [6]:
#Q.5 What is the purpose of the groupby() function in Pandas?
#Create a DataFrame with categorical data (e.g., department & salary) and calculate the average salary per department using groupby(). Explain the output.
data = {
    "Dept":["IT","HR","IT","HR","Sales"],
    "Salary":[50000,40000,60000,45000,30000]
}

df = pd.DataFrame(data)

avg_salary = df.groupby("Dept")["Salary"].mean()
print(avg_salary)

Dept
HR       42500.0
IT       55000.0
Sales    30000.0
Name: Salary, dtype: float64
